#define COLOR_WHITE						0xFFFFFFFF
#define COLOR_GRAD						0xCBCCCEff
#define COLOR_GRAD1						0xb4b5b7ff
#define COLOR_GRAD2						0xa2a2a4ff
#define COLOR_GRAD3						0x909092ff
#define COLOR_GRAD4						0x7d7e80ff
#define COLOR_GRAD5						0x6c6c6dff
#define COLOR_GRAD6						0x5a5a5bff
#define COLOR_GREY						0xAFAFAFFF
#define COLOR_RED						0xFF0000FF
#define COLOR_YELLOW				    0xFFFF00FF
#define COLOR_YELLOW2				    0xEBEB00FF
#define COLOR_YELLOW3				    0xF0EA92AA
#define COLOR_YELLOW4				    0xFFB841FF
#define COLOR_BLUE						0x33CCFFFF
#define COLOR_LIGHTGREEN                0x9ACD32FF
#define COLOR_LIGHTBLUE				    0x33CCFFFF
#define COLOR_LIGHTRED				    0xFF6347FF
#define COLOR_DARKGREEN				    0x88AA62FF
#define COLOR_PINK						0xFF8282FF
#define COLOR_GREEN						0x33AA33FF
#define COLOR_LIGHTCYAN				    0xE0FFFFFF
#define COLOR_LIGHTCYAN2			    0xCCE6E6FF
#define COLOR_PURPLE				    0xC2A2DAFF
#define COLOR_TOMATO				    0xff6347ff
#define COLOR_FADE1						0xE6E6E6E6
#define COLOR_FADE2						0xC8C8C8C8
#define COLOR_FADE3						0xAAAAAAAA
#define COLOR_FADE4						0x8C8C8C8C
#define COLOR_FADE5						0x6E6E6E6E
#define COLOR_FACTION                   0xBDF38BFF
#define TEAM_CUN_COLOR                  0xD900D300
#define COLOR_RADIO                     0x8D8DFFFF
#define COLOR_DARKGOLDENROD             0xB8860BFF
#define TEAM_CYAN_COLOR                 0xFF8282AA
#define COLOR_PMF                       0xF9D718AA
#define COLOR_PMS                       0xF5F260AA
#define COLOR_SPEC                      0xBFC0C2FF

#define PLAYER_COLOR_GREY			    0xAFAFAF00
#define PLAYER_COLOR_WHITE			    0xFFFFFF00
//=======Embed Colors=======
#define EMBED_BLACK                     "{000000}"
#define EMBED_RED						"{FF0000}"
#define EMBED_WHITE						"{FFFFFF}"
#define EMBED_YELLOW				    "{FFFF00}"
#define EMBED_YELLOW2				    "{FFB841}"
#define EMBED_GREEN						"{33AA33}"
#define EMBED_BLUE						"{0000FF}"
#define EMBED_LIGHTBLUE				    "{8080FF}"
#define EMBED_ORANGE				    "{FF8000}"
#define EMBED_GREY						"{AFAFAF}"
#define EMBED_CYAN						"{00FFFF}"
#define EMBED_GRAD						"{CBCCCE}"
#define EMBED_GRAD1						"{b4b5b7}"
#define EMBED_PURPLE				    "{C68DFF}"
#define EMBED_PINK						"{FF8282}"
#define EMBED_LIGHTBLUE2			    "{8D8DFF}"
#define EMBED_LIGHTRED				    "{FF6347}"
#define EMBED_DIALOG				    "{A8C3E3}"
#define EMBED_LIGHTGREEN			    "{AEFFBC}"
#define EMBED_GREENMONEY			    "{33AA33}"
#define EMBED_LIMEGREEN                 "{E5FF00}"
